import 'reflect-metadata';

import { MODULES } from './modules/app.factory';

const APP = MODULES.INFRA.SERVER.HTTP.EXPRESS();

APP.use(MODULES.INFRA.SERVER.HTTP.CORS());
APP.use(MODULES.INFRA.SERVER.HTTP.PARSER.BODY());
APP.use(MODULES.APPLICATION.MIDDLEWARE.LOGGER.APP());
APP.use(MODULES.APPLICATION.ROUTER.HTTP.EXPRESS.APP());
APP.use(MODULES.APPLICATION.ROUTER.HTTP.EXPRESS.EMPLOYEE());
APP.use(MODULES.APPLICATION.MIDDLEWARE.LOGGER.ERROR());
APP.use(MODULES.APPLICATION.MIDDLEWARE.ERROR());

export { APP };
